# Errata {-}

## Preface {-}

page xi, last word of first paragraph is **standaridzation**, 
s/b *standardization*

## Chapter 1 {-}

### Section 1.2.3.2, p. 11 {-}

The sentence of the 6th line on top of the page
is "We simulated the data according to the **hyothetical**", s/b *hypothetical*

## Chapter 2 {-}

### Figure 2.1, p. 30 {-}

This is really a small detail. The caption of the bottom plot is
$\hat{E_{np}}(Y \mid A= 1, H =1, T = 1)$, s/b $\hat{E}_{np}$


## Chapter 3 {-}

### Typography: section 3.2 p. 40, equation 3.1 {-}

The current latex expression of conditional independence used seems to be
`(Y(0), Y(1)) \ \text{II} \ T` with the output

$$
(Y(0), Y(1)) \ \text{II} \ T
$$

a better typography would be `\perp\!\!\!\perp` for the symbol $\perp\!\!\!\perp$. 
When used for  equation 3.1 as `(Y(0), Y(1)) \perp\!\!\!\perp T` we obtain


$$
(Y(0), Y(1)) \perp\!\!\!\perp T
$$

In the case when we want to show dependence, that is *no independence* then
the latex expression is `\not\!\perp\!\!\!\perp` for the symbol
$\not\!\perp\!\!\!\perp$. For example equation 3.1 would become


$$
(Y(0), Y(1)) \not\!\perp\!\!\!\perp T
$$

