# Front-Door Method {#frontdoor}


```{r echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggdag)
# library(dagitty)
library(fciR)
options(dplyr.summarise.inform = FALSE)
```



```{r include=FALSE}
# directory of data files
dir_data <- file.path(getwd(), "data")
# directory for functions
dir_lib <- file.path(getwd(), "lib")
```


## Motivation



```{r echo=TRUE, warning=FALSE}
scm_8.1 <- list()
scm_8.1 <- within(scm_8.1, {
  dag <- dagify(
    A ~ U,
    S ~ A,
    Y ~ S + U)

  plot <- fciR::ggp_dag(dag)
})
```

```{r echo=FALSE, fig.align='center', fig.cap="Front-door Causal DAG", warning=FALSE, out.width="60%"}
scm_8.1$plot
```

> When $S$ is a surrogate marker

$$
\begin{align*}
&\text{by double expectation rule} \\
E(Y \mid A) &= E_{S \mid A}(E(Y \mid A)) \\
&\text{by conditional expectation} \\
&= \sum_s E(Y \mid S=s, A) P(S=s \mid A) \\
&\text{because } Y \perp\!\!\!\perp A \mid S \\
&= \sum_s E(Y \mid S=s) P(S=s \mid A) \\
&\text{since there are no confounder for the effect of A on Y} \\
E(Y(a)) = E(Y \mid A=a) &=  \sum_s E(Y \mid S=s) P(S=s \mid A=a)
\end{align*}
$$

## Theory and Method

Using (8.1) from above


$$
\begin{align*}
E(Y(a)) = E(Y \mid A=a) &=  \sum_s E(Y \mid S=s) P(S=s \mid A=a) \\
&\text{and with backdoor standardization we have that} \\
&E(Y \mid S=s) = \sum_{a^\prime} E(Y \mid S=s, A=a^\prime)P(A = a^\prime) \\
\therefore \\
E(Y(a)) = E(Y \mid A=a) &=  \sum_s P(S=s \mid A=a) \left[ \sum_{a^\prime} E(Y \mid S=s, A=a^\prime)P(A = a^\prime) \right] \\
\end{align*}
$$

and the Front-door causal DAG including potential outcomes is


```{r echo=TRUE, warning=FALSE}
scm_8.4 <- list()
substitute(Y(s))
scm_8.4 <- within(scm_8.4, {
  the_nodes <- c("A" = "", 
                 "U" = "Y(a,s)", 
                 "Sa" = "S(a)",
                 "S" = "",
                 "Y" = "")
  dag <- dagify(
    A ~ U,
    S ~ A + Sa,
    Y ~ S + U,
    labels = the_nodes)

  plot <- fciR::ggp_dag(dag)
})
```

```{r echo=FALSE, fig.align='center', fig.cap="Front-door Causal DAG Including Potential Outcomes", warning=FALSE, out.width="60%"}
scm_8.4$plot
```

## Simulated Example

```{r}
sim1 <- function(n = 1e4, seed = 555) {
  set.seed(seed)
  # Generate the potential outcome Y(.,0) and Y(.,1)
  Ydot0 <- rbinom(n, size = 1, prob = 0.05)
  Ydot1 <- rbinom(n, size = 1, prob = 0.2)
  # let A depend on Y(.,1)
  probA <- (1 - Ydot1) * 0.1 + Ydot1 * 0.8
  A <- rbinom(n, size = 1, prob = probA)
  # Generate the potential outcome S(0) and S(1)
  S0 <- rbinom(n, size = 1, prob = 0.05)
  S1 <- rbinom(n, size = 1, prob = 0.9)
  # S is a function of S0, S1 and A
  S <- (1 - A) * S0 + A * S1
  # Y is a function of Y(., 0) and Y(., 1) and S
  Y <- (1 - S) * Ydot0 + S * Ydot1
  data.frame(cbind(A, S, Y, Ydot0, Ydot1))
}
```


```{r}
sim1_df <- sim1()
sim1.front <- fciR::est_frontdr_np(sim1_df, outcome = "Y", exposure = "A", surrogate = "S")
sim1.front
```

