# (APPENDIX) Appendix {-}

# Errata {#errata}

## Preface

page xi, last word of first paragraph is **standaridzation**, 
s/b *standardization*

## Chapter 1

### Section 1.2.3.2, p. 11

The sentence of the 6th line on top of the page is

> We simulated the data according to the **hyothetical**

Should be *hypothetical*.

## Chapter 2

### Figure 2.1, p. 30

This is really a small detail. The caption of the bottom plot is
$\hat{E_{np}}(Y \mid A= 1, H =1, T = 1)$, s/b $\hat{E}_{np}$


## Chapter 3

### Typography: section 3.2 p. 40, equation 3.1

The current latex expression of conditional independence used seems to be
`(Y(0), Y(1)) \ \text{II} \ T` with the output

$$
(Y(0), Y(1)) \ \text{II} \ T
$$

a better typography would be `\perp\!\!\!\perp` for the symbol $\perp\!\!\!\perp$. 
When used for  equation 3.1 as `(Y(0), Y(1)) \perp\!\!\!\perp T` we obtain


$$
(Y(0), Y(1)) \perp\!\!\!\perp T
$$

In the case when we want to show dependence, that is *no independence* then
the latex expression is `\not\!\perp\!\!\!\perp` for the symbol
$\not\!\perp\!\!\!\perp$. For example equation 3.1 would become


$$
(Y(0), Y(1)) \not\!\perp\!\!\!\perp T
$$

## Chapter 4

### Section 4.1 p. 67 (on top)

The line is

> which is statistically **signficant**

should be *significant*


## Chapter 5

```{r echo=FALSE}
message("nothing found")
```


## Chapter 6

### Section 6.1 p. 100, first paragraph

The second sentence says

> Mistakingly equation $E_H E(Y \mid T=t \mid H)$ with [...]

Should it be $E_H (E(Y \mid T=t) \mid H)$? See extra $)$ before the last $\mid$.

### Section 6.3 p. 126, the script of `simdr`

The last paragraph of p. 126 says

> We simulated $T$ [...] such that approximaly 600 individuals had $T=1$

The `simdr` gives an incorrect result of 540 with the *constant 0.13*. That
constant *should be 0.15* to obtain 600. See the mathematical proof and proof by
simulation in the appendix *Doubly Robust Simulation* at [Analyse $T$](#errata6a).


## Chapter 7

### Section 7.2, equation (7.11), p. 139

> $E(Y_1 \mid A=1) - (E(Y_1\mid A=0, Y_0=1) - E(Y_1\mid A=0, Y_0=0)) - 
E(Y_0 \mid A=0) - (E(Y_1\mid A=0, Y_0=0) - E(Y_1\mid A=0, Y_0=0))$

### Exercise 2

In the last paragraph of the exercise

> In addition, use `exsim.r` to simulate [...]

It should be `ex2sim.r`


## Chapter 8

### Section 8.2, p. 150

The very first sentence of section 8.2 says

> [...] the front-door **theorm** of Pearl [...]

It should be **theorem**
