
```{r}
# directory for functions
dir_lib <- file.path(getwd(), "lib")
```


```{r message=FALSE, warning=FALSE, include=FALSE}
source(file = file.path(dir_lib, "gt_measures.R"))
```


# Functions

All the scripts for the functions below can be found at 
[study project](https://github.com/FrankLef/FundamentalsCausalInference), mostly in the
`/lib` folder.

The functions are shown in order of appearance in the chapter where they are
first used.

## Chapter 3

### `gt_measures.R`

```{r, file="lib\\gt_measures.R"}

```


## Chapter 4

### `gt_measures_modif.R`


```{r, file="lib\\gt_measures_modif.R"}

```


### `ggp_measures_modif.R`

```{r, file="lib\\ggp_measures_modif.R"}

```


### `betasim_effect_measures.R`


```{r, file="lib\\betasim_effect_measures.R"}

```


### `ggp_venn_sim.R`


```{r, file="lib\\ggp_venn_sim.R"}

```


### `ggp_betasim.R`


```{r, file="lib\\ggp_betasim.R"}

```


## Chapter 5

### `ggp_dag.R`


```{r file="lib\\ggp_dag.R"}

```

### `gt_probs.R`


```{r file="lib\\gt_probs.R"}

```

