--- 
title: "Study project: Fundamentals of Causal Inferences With R"
author: "François Lefebvre"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [books.bib, packages.bib]
description: |
  This is a study project of Fundamentals of Causal Inferences by Babette A.
  Brumback. It goes through a lot of the codes and through many mathematical
  arguments for better learning.  All exercises are attempted.
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# Study Project {-}

## About {-}

This is a study project of @brumback2022. Many thanks to Babette Brumback for a 
great book to tackle the question of causality.  All my gratitude goes to 
Ms Brumback for such a useful and much needed book.

The suggestions for errata are in the section *Errata*. Comments are also
included in the section *Comments*.

## Packages {-}

The functions have been rewritten to simplify them and improve the
learning experience (personal opinion) for newbies such as me.

The following packages are so useful that they
could not be avoided. In particular, `dplyr` and `tidyr` make the coding 
experience so much more interesting that one could almost claim they have become
the standard in `R` coding.

* `dplyr` for data wrangling. see @R-dplyr
* `tidyr` for data wrangling. see @R-tidyr
* `ggplot2` for plots, see @R-ggplot2`
* `gt` for all tables, see @R-gt
* `dagitty` for analysis of structural causal models, see @R-dagitty
* `ggdag` for directed acyclic graphs, see @R-ggdag
* `gee`: a generalized estimation equation solver. Introduced in chapter 4.
See @R-gee.
* `MonteCarlo`: To perform Monte Carlo simulations. Introduced in chapter 4,
section 4.2. See @R-MonteCarlo.
* `simstudy`: To run all sorts of simulations. A great tool to learn right from the
start since simulations are so important. See @R-simstudy.
